name: Bot de Preços Diário

on:
  schedule:
    # Roda todos os dias às 11:00 UTC (08:00 no horário de Brasília)
    - cron: '0 11 * * *'
  workflow_dispatch: # Cria um botão para podermos testar manualmente!

jobs:
  rodar-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Puxar o código do repositório
        uses: actions/checkout@v3

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: Rodar o Scrapper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python scrapper.py